const S = {
  app: { fontFamily: "'DM Sans','Segoe UI',system-ui,sans-serif", background: "#1A1D23", color: "#F0F0F0", minHeight: "100vh", paddingBottom: 90, maxWidth: 480, margin: "0 auto" },
  loadWrap: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100vh", background: "#1A1D23" },
  loadIcon: { fontSize: 48, marginBottom: 16 }, loadText: { fontSize: 14, color: "#666" },
  dashHeader: { padding: "24px 20px 8px", display: "flex", alignItems: "center", gap: 12 },
  dashIcon: { fontSize: 28 }, dashTitle: { fontSize: 20, fontWeight: 800, letterSpacing: "-0.5px" },
  dashYear: { fontSize: 13, color: "#E67E22", fontWeight: 700, background: "rgba(230,126,34,0.15)", padding: "4px 10px", borderRadius: 8, marginLeft: "auto" },
  summaryGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, padding: "12px 20px" },
  sumCard: { background: "#22252C", borderRadius: 12, padding: "12px 14px" },
  sumCardWide: { gridColumn: "1 / -1", textAlign: "center" },
  sumLabel: { fontSize: 10, color: "#888", textTransform: "uppercase", letterSpacing: 1, marginBottom: 2, fontWeight: 600 },
  sumBig: { fontSize: 28, fontWeight: 800, color: "#E67E22", letterSpacing: "-1px" },
  sumMed: { fontSize: 20, fontWeight: 700 }, sumSub: { fontSize: 11, color: "#555", marginTop: 1 },
  sectionTitle: { fontSize: 13, fontWeight: 700, color: "#666", padding: "14px 20px 6px", textTransform: "uppercase", letterSpacing: 1 },
  sectionTitleBtn: { display: "flex", justifyContent: "space-between", width: "100%", padding: "14px 20px 6px", background: "none", border: "none", color: "#666", fontSize: 13, fontWeight: 700, textTransform: "uppercase", letterSpacing: 1, cursor: "pointer", fontFamily: "inherit" },
  barChart: { padding: "0 20px" },
  barRow: { display: "flex", alignItems: "center", gap: 8, padding: "6px 0", border: "none", background: "none", color: "#F0F0F0", width: "100%", cursor: "pointer", textAlign: "left", fontFamily: "inherit" },
  barLabel: { width: 30, fontSize: 11, color: "#888", fontWeight: 600, flexShrink: 0 },
  barTrack: { flex: 1, height: 18, background: "#2A2D35", borderRadius: 5, position: "relative", overflow: "hidden" },
  barFill: { position: "absolute", top: 0, left: 0, height: "100%", background: "#E67E22", borderRadius: 5, transition: "width 0.5s", zIndex: 2 },
  barEstFill: { position: "absolute", top: 0, left: 0, height: "100%", background: "#F5CBA7", borderRadius: 5, opacity: 0.35, zIndex: 1 },
  barAmt: { width: 52, fontSize: 11, color: "#AAA", fontWeight: 600, textAlign: "right", flexShrink: 0 },
  legendRow: { display: "flex", gap: 16, padding: "8px 20px", justifyContent: "center" },
  legendItem: { display: "flex", alignItems: "center", gap: 6, fontSize: 10, color: "#888" },
  legendDot: { width: 8, height: 8, borderRadius: 2 },
  clientMini: { display: "flex", justifyContent: "space-between", padding: "8px 20px", borderBottom: "1px solid #2A2D35" },
  clientMiniName: { fontSize: 14, fontWeight: 600 }, clientMiniProfit: { fontSize: 14, fontWeight: 700 },
  monthNav: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "20px 20px 8px" },
  navArrow: { background: "#22252C", border: "none", color: "#E67E22", fontSize: 16, borderRadius: 10, width: 38, height: 38, cursor: "pointer", fontFamily: "inherit" },
  monthTitle: { fontSize: 20, fontWeight: 800, letterSpacing: "-0.5px" },
  miniDash: { padding: "8px 20px 12px" },
  miniRow: { display: "flex", gap: 8, marginBottom: 6 },
  miniCard: { flex: 1, background: "#22252C", borderRadius: 10, padding: "10px 12px" },
  miniLabel: { fontSize: 10, color: "#888", textTransform: "uppercase", letterSpacing: 0.8, fontWeight: 600, marginBottom: 1 },
  miniVal: { fontSize: 18, fontWeight: 800 },
  estVsActual: { fontSize: 11, color: "#E67E22", fontWeight: 600, textAlign: "center", padding: "2px 0" },
  weeksList: { padding: "0 20px" }, weekBlock: { marginBottom: 14 },
  weekHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 5 },
  weekLabel: { fontSize: 12, fontWeight: 700, color: "#555", textTransform: "uppercase", letterSpacing: 0.8 },
  weekTotal: { fontSize: 12, fontWeight: 700, color: "#E67E22", display: "flex", alignItems: "center", gap: 6 },
  weekTotals: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" },
  weekEarned: { fontSize: 12, fontWeight: 700, color: "#E67E22" },
  weekEstimated: { fontSize: 11, fontWeight: 600, color: "#3498DB" },
  weekDash: { fontSize: 12, color: "#444" },
  bestBadge: { fontSize: 8, background: "#27AE60", color: "#fff", padding: "2px 5px", borderRadius: 3, fontWeight: 700, textTransform: "uppercase" },
  dayGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(54px, 1fr))", gap: 5 },
  dayCell: { background: "#22252C", borderRadius: 8, padding: "6px 3px", textAlign: "center", border: "2px solid transparent", cursor: "pointer", fontFamily: "inherit", color: "#F0F0F0", display: "flex", flexDirection: "column", alignItems: "center", minHeight: 64 },
  dayCellWknd: { background: "#1E2026", opacity: 0.45 },
  dayCellFilled: { borderColor: "#E67E22", background: "rgba(230,126,34,0.08)" },
  dayCellEstimated: { borderColor: "#3498DB", background: "rgba(52,152,219,0.08)" },
  dayCellToday: { borderColor: "#3498DB", boxShadow: "0 0 0 1px rgba(52,152,219,0.3)" },
  dayName: { fontSize: 8, color: "#555", fontWeight: 600, textTransform: "uppercase" },
  dayNum: { fontSize: 14, fontWeight: 700, margin: "1px 0" },
  dayAmt: { fontSize: 9, color: "#E67E22", fontWeight: 700 },
  dayAmtEst: { fontSize: 9, color: "#3498DB", fontWeight: 700 },
  dayClient: { fontSize: 7, color: "#888", fontWeight: 500, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", maxWidth: "100%" },
  dayPlus: { fontSize: 14, color: "#444", fontWeight: 300 },
  entryHeader: { display: "flex", alignItems: "center", gap: 16, padding: "20px 20px 12px" },
  backBtn: { background: "none", border: "none", color: "#E67E22", fontSize: 15, fontWeight: 600, cursor: "pointer", padding: 0, fontFamily: "inherit" },
  entryDate: { display: "flex", alignItems: "baseline", gap: 8 },
  entryDay: { fontSize: 13, color: "#888", fontWeight: 600 },
  entryDateNum: { fontSize: 20, fontWeight: 800 },
  entryTitle: { fontSize: 20, fontWeight: 800 },
  formWrap: { padding: "0 20px 20px" },
  fieldGroup: { marginBottom: 12 },
  label: { display: "block", fontSize: 11, color: "#888", fontWeight: 600, marginBottom: 3, textTransform: "uppercase", letterSpacing: 0.5 },
  input: { width: "100%", padding: "11px 12px", borderRadius: 8, border: "2px solid #2A2D35", background: "#22252C", color: "#F0F0F0", fontSize: 15, fontFamily: "inherit", boxSizing: "border-box" },
  row: { display: "flex", gap: 8 },
  half: { flex: 1, marginBottom: 12 },
  divider: { height: 1, background: "#2A2D35", margin: "8px 0 12px" },
  saveBtn: { width: "100%", padding: "14px", borderRadius: 10, border: "none", background: "#E67E22", color: "#fff", fontSize: 15, fontWeight: 700, cursor: "pointer", marginTop: 16, fontFamily: "inherit", transition: "all 0.3s" },
  saveBtnFlash: { background: "#27AE60" },
  deleteBtn: { width: "100%", padding: "12px", borderRadius: 10, border: "2px solid #333", background: "transparent", color: "#E74C3C", fontSize: 13, fontWeight: 600, cursor: "pointer", marginTop: 8, fontFamily: "inherit" },
  overheadSummary: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, padding: "12px 20px" },
  ohCard: { background: "#22252C", borderRadius: 12, padding: "12px 14px" },
  ohCardWide: { gridColumn: "1 / -1", textAlign: "center" },
  ohLabel: { fontSize: 10, color: "#888", textTransform: "uppercase", letterSpacing: 1, fontWeight: 600, marginBottom: 2 },
  ohVal: { fontSize: 20, fontWeight: 800, color: "#F0F0F0" },
  ohValBig: { fontSize: 26, fontWeight: 800 },
  ohPer: { fontSize: 12, color: "#888", fontWeight: 500 },
  ohSubtext: { fontSize: 11, color: "#555", marginTop: 2 },
  emptyWrap: { textAlign: "center", padding: "30px 20px" },
  emptyText: { fontSize: 14, color: "#555", padding: "8px 20px" },
  expRow: { display: "flex", alignItems: "center", gap: 10, padding: "10px 20px", borderBottom: "1px solid #2A2D35" },
  expIcon: { fontSize: 20, width: 32, textAlign: "center" },
  expInfo: { flex: 1 }, expName: { fontSize: 14, fontWeight: 600 }, expCat: { fontSize: 11, color: "#666" },
  expAmount: { fontSize: 15, fontWeight: 700, color: "#E74C3C" },
  expPer: { fontSize: 10, color: "#888", fontWeight: 500 },
  expSplitBtn: { background: "rgba(52,152,219,0.12)", border: "1px solid #3498DB", color: "#3498DB", fontSize: 10, fontWeight: 700, borderRadius: 6, cursor: "pointer", padding: "3px 8px", marginRight: 6, fontFamily: "inherit" },
  expDel: { background: "none", border: "none", color: "#555", fontSize: 14, cursor: "pointer", padding: 4 },
  addExpBtn: { display: "block", margin: "16px 20px", padding: "14px", borderRadius: 10, border: "2px dashed #333", background: "transparent", color: "#E67E22", fontSize: 14, fontWeight: 700, cursor: "pointer", textAlign: "center", fontFamily: "inherit", width: "calc(100% - 40px)" },
  toggleRow: { display: "flex", gap: 0, marginBottom: 12, borderRadius: 8, overflow: "hidden", border: "2px solid #2A2D35" },
  toggleBtn: { flex: 1, padding: "10px", background: "#22252C", border: "none", color: "#888", fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
  toggleBtnActive: { flex: 1, padding: "10px", background: "#E67E22", border: "none", color: "#fff", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  heroCard: { margin: "0 20px 12px", borderRadius: 16, padding: "20px", border: "1px solid", textAlign: "center" },
  heroLabel: { fontSize: 11, color: "#888", fontWeight: 700, textTransform: "uppercase", letterSpacing: 1, marginBottom: 6 },
  heroAmount: { fontSize: 44, fontWeight: 900, lineHeight: 1, marginBottom: 4 },
  heroSub: { fontSize: 12, color: "#666" },
  statRow: { display: "flex", gap: 8, padding: "0 20px 10px" },
  statPill: { flex: 1, background: "#22252C", borderRadius: 12, padding: "10px 8px", textAlign: "center" },
  statPillLabel: { fontSize: 9, color: "#666", textTransform: "uppercase", letterSpacing: 0.8, fontWeight: 700, marginBottom: 3 },
  statPillVal: { fontSize: 16, fontWeight: 800, color: "#F0F0F0" },
  clientCard: { margin: "8px 20px", background: "#22252C", borderRadius: 12, padding: "14px 16px" },
  clientHeader: { display: "flex", alignItems: "center", gap: 8 },
  clientRank: { fontSize: 12, color: "#555", fontWeight: 700, width: 24 },
  clientName: { flex: 1, fontSize: 16, fontWeight: 700 },
  clientProfit: { fontSize: 18, fontWeight: 800 },
  clientBar: { height: 4, background: "#2A2D35", borderRadius: 2, margin: "8px 0", overflow: "hidden" },
  clientBarFill: { height: "100%", background: "#E67E22", borderRadius: 2, transition: "width 0.5s" },
  clientDetails: { display: "flex", gap: 8 },
  clientStat: { flex: 1, fontSize: 12, color: "#999", display: "flex", flexDirection: "column", alignItems: "center" },
  clientStatLbl: { fontSize: 9, color: "#555", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 1 },
  schedForecast: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 20px", background: "#22252C", margin: "0 20px 12px", borderRadius: 10 },
  schedForecastLabel: { fontSize: 12, color: "#888", fontWeight: 600, textTransform: "uppercase" },
  schedForecastVal: { fontSize: 22, fontWeight: 800, color: "#E67E22" },
  schedDayList: { padding: "0 20px" },
  schedDayCard: { display: "flex", alignItems: "center", gap: 10, padding: "12px 14px", background: "#22252C", borderRadius: 10, marginBottom: 6, border: "2px solid transparent", cursor: "pointer", width: "100%", textAlign: "left", fontFamily: "inherit", color: "#F0F0F0" },
  schedDayToday: { borderColor: "#3498DB" },
  schedDayWknd: { opacity: 0.4 },
  schedDayLeft: { width: 44, textAlign: "center", flexShrink: 0 },
  schedDayName: { fontSize: 10, color: "#888", fontWeight: 700, textTransform: "uppercase" },
  schedDayNum: { fontSize: 20, fontWeight: 800 },
  schedDayMonth: { fontSize: 9, color: "#555" },
  schedDayRight: { flex: 1, display: "flex", flexDirection: "column", gap: 4 },
  schedEmpty: { fontSize: 12, color: "#444" },
  schedJobPill: { background: "rgba(230,126,34,0.1)", borderRadius: 6, padding: "6px 10px", borderLeft: "3px solid #E67E22" },
  schedJobClient: { fontSize: 13, fontWeight: 700 },
  schedJobName: { fontSize: 11, color: "#888" },
  schedDayEarn: { textAlign: "right", flexShrink: 0 },
  schedDayExpected: { fontSize: 14, fontWeight: 700, color: "#E67E22" },
  schedDayActual: { fontSize: 10, color: "#27AE60", fontWeight: 600 },
  schedSlot: { background: "#22252C", borderRadius: 10, padding: "14px", marginBottom: 10, borderLeft: "3px solid #E67E22" },
  schedSlotHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  schedSlotTitle: { fontSize: 14, fontWeight: 700, color: "#E67E22" },
  schedSlotDel: { background: "none", border: "none", color: "#555", fontSize: 16, cursor: "pointer" },
  editBookingBtn: { background: "rgba(52,152,219,0.15)", border: "none", color: "#3498DB", fontSize: 12, fontWeight: 700, padding: "4px 10px", borderRadius: 6, cursor: "pointer", fontFamily: "inherit" },
  bookingInfo: { fontSize: 13, color: "#AAA", marginTop: 2 },
  bookingDates: { fontSize: 11, color: "#666", marginTop: 2 },
  sectionTitle2: { fontSize: 12, fontWeight: 700, color: "#555", textTransform: "uppercase", letterSpacing: 0.8, padding: "12px 0 6px" },
  completeJobBtn: { width: "100%", padding: "14px", borderRadius: 10, border: "2px solid #27AE60", background: "rgba(39,174,96,0.1)", color: "#27AE60", fontSize: 15, fontWeight: 700, cursor: "pointer", marginTop: 8, fontFamily: "inherit" },
  jobCard: { margin: "8px 20px", background: "#22252C", borderRadius: 12, padding: "14px 16px" },
  jobCardHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
  jobCardClient: { fontSize: 16, fontWeight: 700 },
  jobCardJob: { fontSize: 13, color: "#888" },
  jobCardProfit: { fontSize: 20, fontWeight: 800 },
  jobCardDates: { fontSize: 11, color: "#666", margin: "6px 0" },
  jobCardStats: { display: "flex", gap: 6, marginTop: 6 },
  jobCardStat: { flex: 1, fontSize: 11, color: "#999", display: "flex", flexDirection: "column", alignItems: "center", background: "#1A1D23", borderRadius: 6, padding: "6px 4px" },
  jobCardStatLbl: { fontSize: 8, color: "#555", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 1 },
  jobCardNotes: { fontSize: 12, color: "#888", marginTop: 6, fontStyle: "italic" },
  jobBookedBadge: { fontSize: 10, fontWeight: 800, color: "#3498DB", background: "rgba(52,152,219,0.12)", padding: "4px 10px", borderRadius: 6, marginBottom: 10, letterSpacing: 0.4, display: "inline-block" },
  jobBookedActions: { display: "flex", gap: 8, marginTop: 12 },
  jobRemoveBtn: { flex: 1, padding: "10px 12px", borderRadius: 8, border: "1px solid #444", background: "transparent", color: "#888", fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
  calJobsHint: { fontSize: 11, color: "#666", margin: "-4px 20px 12px", textAlign: "center", lineHeight: 1.4 },
  addSlotBtn: { width: "100%", padding: "12px", borderRadius: 8, border: "2px dashed #333", background: "transparent", color: "#3498DB", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "inherit", marginBottom: 8 },
  schedHint: { background: "rgba(52,152,219,0.1)", margin: "0 20px 12px", borderRadius: 8, padding: "10px 14px", borderLeft: "3px solid #3498DB" },
  schedHintLabel: { fontSize: 11, fontWeight: 700, color: "#3498DB", marginBottom: 4 },
  schedHintItem: { fontSize: 13, color: "#AAA" },
  bookRangeBtn: { display: "block", margin: "0 20px 12px", padding: "12px 16px", borderRadius: 10, border: "2px solid #E67E22", background: "rgba(230,126,34,0.08)", color: "#E67E22", fontSize: 14, fontWeight: 700, cursor: "pointer", textAlign: "center", fontFamily: "inherit", width: "calc(100% - 40px)" },
  weekendToggles: { display: "flex", flexDirection: "column", gap: 0 },
  weekendToggle: { display: "flex", alignItems: "center", gap: 12, padding: "12px 0", background: "none", border: "none", color: "#F0F0F0", fontSize: 14, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
  weekendBox: { width: 24, height: 24, borderRadius: 6, border: "2px solid #444", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, color: "#E67E22", flexShrink: 0 },
  weekendBoxChecked: { background: "rgba(230,126,34,0.15)", borderColor: "#E67E22" },
  rangePreview: { background: "#22252C", borderRadius: 10, padding: "12px 14px", marginTop: 8 },
  rangePreviewRow: { display: "flex", justifyContent: "space-between", padding: "4px 0" },
  rangePreviewLabel: { fontSize: 13, color: "#888" },
  rangePreviewVal: { fontSize: 13, color: "#F0F0F0", fontWeight: 600 },
  settingsHelp: { fontSize: 12, color: "#888", marginTop: 6 },
  calHeader: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 3, marginBottom: 4 },
  calHeaderDay: { fontSize: 10, color: "#555", fontWeight: 700, textAlign: "center", padding: 4 },
  calGrid: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 3 },
  calCell: { aspectRatio: "1", borderRadius: 6, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", minHeight: 44 },
  calCellBtn: { background: "#22252C", border: "2px solid transparent", cursor: "pointer", fontFamily: "inherit", color: "#F0F0F0", padding: 2 },
  calCellToday: { borderColor: "#3498DB" },
  calCellFilled: { borderColor: "#E67E22", background: "rgba(230,126,34,0.08)" },
  calCellNum: { fontSize: 13, fontWeight: 700 },
  calCellDot: { width: 6, height: 6, borderRadius: 3, background: "#E67E22", marginTop: 2, fontSize: 0 },
  calCellClient: { fontSize: 7, color: "#888", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", maxWidth: "100%" },
  quickOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.45)", border: "none", zIndex: 120 },
  quickMenu: { position: "fixed", left: "50%", bottom: 84, transform: "translateX(-50%)", width: "calc(100% - 40px)", maxWidth: 440, background: "#22252C", border: "1px solid #2A2D35", borderRadius: 14, padding: 10, zIndex: 130, boxShadow: "0 8px 30px rgba(0,0,0,0.35)" },
  quickMenuLabel: { fontSize: 9, fontWeight: 700, color: "#555", textTransform: "uppercase", letterSpacing: 1, padding: "4px 12px 2px" },
  quickItem: { width: "100%", textAlign: "left", padding: "11px 12px", background: "transparent", border: "none", color: "#F0F0F0", fontSize: 14, fontWeight: 600, borderRadius: 8, cursor: "pointer", fontFamily: "inherit" },
  undoBar: { position: "fixed", left: "50%", transform: "translateX(-50%)", bottom: 86, width: "calc(100% - 40px)", maxWidth: 440, background: "#0F1116", border: "1px solid #2A2D35", borderRadius: 12, padding: "10px 12px", display: "flex", alignItems: "center", justifyContent: "space-between", zIndex: 125, boxShadow: "0 8px 26px rgba(0,0,0,0.35)" },
  undoTxt: { fontSize: 13, color: "#B9BDC7", fontWeight: 600 },
  undoBtn: { background: "rgba(230,126,34,0.15)", border: "1px solid #E67E22", color: "#E67E22", borderRadius: 8, padding: "6px 10px", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  bottomNav: { position: "fixed", bottom: 0, left: 0, right: 0, display: "flex", justifyContent: "space-evenly", alignItems: "center", background: "#16181D", borderTop: "1px solid #2A2D35", padding: "6px 0 18px", zIndex: 100, maxWidth: 480, margin: "0 auto" },
  navBtn: { background: "none", border: "none", color: "#555", display: "flex", flexDirection: "column", alignItems: "center", gap: 1, cursor: "pointer", padding: "4px 3px", fontFamily: "inherit" },
  navActive: { color: "#E67E22" },
  navIcon: { fontSize: 17 }, navTxt: { fontSize: 8, fontWeight: 600, textTransform: "uppercase", letterSpacing: 0.3 },
  navAdd: { width: 48, height: 48, borderRadius: 24, background: "#E67E22", border: "none", color: "#fff", fontSize: 26, cursor: "pointer", marginTop: -18, boxShadow: "0 4px 16px rgba(230,126,34,0.4)", display: "flex", alignItems: "center", justifyContent: "center" },
  toastBar: { position: "fixed", left: "50%", transform: "translateX(-50%)", top: 20, width: "calc(100% - 40px)", maxWidth: 440, background: "#27AE60", color: "#fff", borderRadius: 10, padding: "12px 14px", display: "flex", alignItems: "center", justifyContent: "space-between", zIndex: 200, boxShadow: "0 4px 20px rgba(0,0,0,0.4)", fontSize: 14, fontWeight: 600 },
  toastBarError: { background: "#E74C3C" },
  toastClose: { background: "none", border: "none", color: "#fff", fontSize: 20, cursor: "pointer", padding: "0 0 0 12px", lineHeight: 1, fontFamily: "inherit" },
  confirmOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", border: "none", zIndex: 150 },
  confirmBox: { position: "fixed", left: "50%", top: "50%", transform: "translate(-50%,-50%)", width: "calc(100% - 48px)", maxWidth: 360, background: "#22252C", border: "1px solid #2A2D35", borderRadius: 14, padding: "24px 20px", zIndex: 155, boxShadow: "0 12px 40px rgba(0,0,0,0.5)" },
  confirmMsg: { fontSize: 15, fontWeight: 600, color: "#F0F0F0", marginBottom: 20, lineHeight: 1.5 },
  confirmBtns: { display: "flex", gap: 10 },
  confirmCancel: { flex: 1, padding: "12px", borderRadius: 10, border: "1px solid #333", background: "transparent", color: "#888", fontSize: 14, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
  confirmOk: { flex: 1, padding: "12px", borderRadius: 10, border: "none", background: "#E74C3C", color: "#fff", fontSize: 14, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  searchInput: { width: "100%", padding: "10px 12px", borderRadius: 8, border: "2px solid #2A2D35", background: "#22252C", color: "#F0F0F0", fontSize: 14, fontFamily: "inherit", boxSizing: "border-box", outline: "none" },
  repeatBtn: { width: "100%", padding: "12px 14px", borderRadius: 10, border: "2px solid #3498DB", background: "rgba(52,152,219,0.08)", color: "#3498DB", fontSize: 13, fontWeight: 700, cursor: "pointer", marginBottom: 14, fontFamily: "inherit", textAlign: "left", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  invoiceBtn: { width: "100%", padding: "13px", borderRadius: 10, border: "2px solid #27AE60", background: "rgba(39,174,96,0.08)", color: "#27AE60", fontSize: 14, fontWeight: 700, cursor: "pointer", marginTop: 8, fontFamily: "inherit" },
  invoiceDoc: { margin: "16px 16px 0", background: "#fff", borderRadius: 12, padding: "24px 22px", color: "#1a1a1a", boxShadow: "0 4px 24px rgba(0,0,0,0.3)" },
  invoiceHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16 },
  invoiceBizName: { fontSize: 18, fontWeight: 800, color: "#1a1a1a", marginBottom: 4 },
  invoiceBizDetail: { fontSize: 12, color: "#555", lineHeight: 1.5 },
  invoiceTitle: { fontSize: 22, fontWeight: 900, color: "#1a1a1a", letterSpacing: 2, textTransform: "uppercase" },
  invoiceNum: { fontSize: 15, fontWeight: 700, color: "#E67E22" },
  invoiceMeta: { fontSize: 12, color: "#555" },
  invoiceDivider: { height: 1, background: "#e5e5e5", margin: "14px 0" },
  invoiceSectionLabel: { fontSize: 9, fontWeight: 800, color: "#999", textTransform: "uppercase", letterSpacing: 1.2, marginBottom: 6 },
  invoiceClientName: { fontSize: 16, fontWeight: 700, color: "#1a1a1a" },
  invoiceClientDetail: { fontSize: 12, color: "#555", lineHeight: 1.6 },
  invoiceJobBox: { background: "#f7f8fa", borderRadius: 8, padding: "10px 14px", marginBottom: 16, borderLeft: "3px solid #E67E22" },
  invoiceJobTitle: { fontSize: 14, fontWeight: 700, color: "#1a1a1a" },
  invoiceJobMeta: { fontSize: 11, color: "#777", marginTop: 2 },
  invoiceTable: { marginBottom: 0 },
  invoiceTableHead: { display: "flex", justifyContent: "space-between", fontSize: 9, fontWeight: 800, color: "#999", textTransform: "uppercase", letterSpacing: 1, padding: "6px 0", borderBottom: "1px solid #e5e5e5", marginBottom: 4 },
  invoiceLineItem: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", padding: "8px 0", borderBottom: "1px solid #f0f0f0" },
  invoiceLineDesc: { display: "flex", flexDirection: "column", flex: 1, marginRight: 12, fontSize: 13, color: "#1a1a1a", fontWeight: 500 },
  invoiceLineSub: { fontSize: 11, color: "#999", fontWeight: 400, marginTop: 1 },
  invoiceLineAmt: { fontSize: 13, fontWeight: 700, color: "#1a1a1a", flexShrink: 0 },
  invoiceTotalRow: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 0 0", borderTop: "2px solid #1a1a1a", marginTop: 4 },
  invoiceTotalLabel: { fontSize: 13, fontWeight: 800, color: "#1a1a1a", textTransform: "uppercase", letterSpacing: 0.5 },
  invoiceTotalAmt: { fontSize: 22, fontWeight: 900, color: "#1a1a1a" },
  invoicePayDetail: { display: "flex", gap: 10, fontSize: 13, color: "#1a1a1a", padding: "3px 0" },
  invoicePayLabel: { fontSize: 11, fontWeight: 700, color: "#999", width: 70, flexShrink: 0 },
  invoiceThankYou: { fontSize: 13, color: "#777", fontStyle: "italic", textAlign: "center", marginTop: 4 },
};

export default S;
